version: "3.7"
services:
  app:
    image: ghcr.io/ryukyungwoo/personal-project-fastapi:latest
    container_name: docker-fast-api-deploy-server
    ports:
      - 8000:8000
    networks:
      - app

networks:
  app:
    driver: bridge